management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8088
    servlet:
        context-path: /system-local
spring:
    application:
        name: autosys-system
