management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8080
    servlet:
        context-path: /system-dev
spring:
    application:
        name: autosys-system
