management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 9000
    servlet:
        context-path: /generator-local
spring:
    application:
        name: autosys-generator
